name: ci

on:
  push:
    branches:
      - 'containerize'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:.devcontainer"
          push: true
          tags: ghcr.io/liesnikov/group-workshop:latest
          cache-from: type=registry,ref=ghcr.io/liesnikov/group-workshop:buildcache
          cache-to: type=registry,ref=ghcr.io/liesnikov/group-workshop:buildcache,mode=max
